// Kapsam matrisi: hangi özellik hangi senaryoyla kanıtlanıyor. Kanıt sayfası
// bunu koşu sonuçlarıyla birleştirip en üste koyar (Geçti / Kaldı / Koşmadı).
//
// Her satır: { id, group, feature, scenarios } — scenarios, tests/ altındaki
// dosya adı önekleri ("13" → tests/13-*.spec.js). Bir özellik birden fazla
// senaryoyla kanıtlanabilir; hepsi geçerse satır "Geçti"dir.
//
// Gruplar: K sıfırdan kurulum, A pin yönetimi ve imzalı config, B mTLS
// (istemci sertifikası), C vault (uzaktan dosya dağıtımı), D telefonda şifreli
// saklama, E sunucu işletimi, F sunucuya ulaşılamadığında, G araya girme
// saldırıları, H kendi sunucusuyla ya da sunucusuz kullanım, S imza
// anahtarlarının korunması (isteğe bağlı), Y değişiklik denetimi ve onay
// (isteğe bağlı). Grup ajanları kendi satırlarını ekler; PLAN.md bölüm 3 ile
// aynı adlandırma.

const GROUPS = {
  K: 'Sıfırdan kurulum',
  A: 'Pin yönetimi ve imzalı config',
  B: 'mTLS (istemci sertifikası)',
  C: 'Vault (uzaktan dosya dağıtımı)',
  D: 'Telefonda şifreli saklama',
  E: 'Sunucu işletimi',
  F: 'Sunucuya ulaşılamadığında',
  G: 'Araya girme saldırıları',
  H: 'Kendi sunucusuyla ya da sunucusuz kullanım',
  S: 'İmza anahtarlarının korunması (isteğe bağlı)',
  Y: 'Değişiklik denetimi ve onay (isteğe bağlı)',
};

const FEATURES = [
  // ── K (sıfırdan kurulum) ──────────────────────────────────────────────
  { id: 'K-gereksinim', group: 'K', feature: 'Gereksinimler ve depo düzeni: docker, node, java, adb, openssl sürümleri; yan yana duran dört depo', scenarios: ['K01'] },
  { id: 'K-setup', group: 'K', feature: 'scripts/setup.sh .env\'i üretiyor (API anahtarı, LAN IP), signing-key.pem\'i 0600 izinle yazıyor; API_KEY boşken compose başlamıyor', scenarios: ['K01'] },
  { id: 'K-compose', group: 'K', feature: 'docker compose up -d --build, sağlık kontrolü (healthcheck), Flyway migration\'ları, provision.sh, smoke-test.sh (0 FAIL)', scenarios: ['K01'] },
  { id: 'K-dashboard-giris', group: 'K', feature: 'Dashboard ilk açılışta API anahtarı soruyor; yanlış anahtar reddediliyor (401/403), doğru anahtarla giriş yapılıyor', scenarios: ['K02'] },
  { id: 'K-config-api-sekme', group: 'K', feature: 'Config API sekmeleri: Genel, Bootstrap (APK\'ya gömülecek pin\'ler + kod parçası), İmzalama (public key); sunucu sertifikası LAN IP\'yi de kapsıyor (SAN)', scenarios: ['K02'] },
  { id: 'K-host-ekleme', group: 'K', feature: 'Host ekleme üç yolla: elle pin, sunucuda sertifika üretme, URL\'den pin çekme; hatalı biçimli pin reddediliyor', scenarios: ['K03'] },
  { id: 'K-host-yukleme', group: 'K', feature: 'Host eklemenin dördüncü yolu: "Dosya Yükle" sekmesinden JKS/P12 dosyası (upload-cert); pin\'ler yüklenen sertifikadan hesaplanıyor', scenarios: ['K03'] },
  { id: 'K-mtls-api', group: 'K', feature: 'mTLS Config API: istemci sertifikası yokken (truststore yok) 400, sertifika üretilince açılıyor', scenarios: ['K04'] },
  { id: 'K-mock-host', group: 'K', feature: 'Test için kurulan hedef sunucular (mock host): başlatma, durum rozeti, "Bağlantıyı Test Et"', scenarios: ['K04'] },
  { id: 'K-vault-yukleme', group: 'K', feature: 'Vault yükleme: metin ve dosya, politika × şifreleme, dosya listesi ve detayı; at_rest dosyası sunucu diskinde şifreli', scenarios: ['K05'] },
  { id: 'K-istemci-degerleri', group: 'K', feature: 'client-config.sh --properties çıktısı BuildConfig\'e giriyor; network_security_config; gradle ile derleme ve adb install', scenarios: ['K06'] },
  { id: 'K-ilk-baglanti', group: 'K', feature: 'İlk açılışta "Hazır — config vN"; cihaz dashboard\'da Bağlı Cihazlar ve Bağlantı Geçmişi\'nde görünüyor', scenarios: ['K06'] },
  { id: 'K-docs', group: 'K', feature: 'Swagger UI (/docs) ve openapi.yaml; dashboard TR/EN; tablo sayfalaması', scenarios: ['K07'] },
  // ── E (sunucu işletimi) ───────────────────────────────────────────────
  { id: 'E-imzalama-sifreli', group: 'E', feature: 'SIGNING_KEY_PASSWORD: anahtar diskte AES-256-GCM ile şifreli (ENCv1:), düz dosya kendiliğinden çevriliyor, imza doğrulanmaya devam ediyor', scenarios: ['E01'] },
  { id: 'E-yetki', group: 'E', feature: 'Yönetim uçları anahtarsız 401, yanlış anahtarla 403; cihaz uçları anahtar istemiyor; yanıtlarda güvenlik başlıkları var', scenarios: ['E02'] },
  { id: 'E-anonim', group: 'E', feature: 'API_KEY yokken sunucu açılmıyor; ALLOW_ANONYMOUS_ADMIN=true ile açılırsa loga uyarı yazıyor', scenarios: ['E02'] },
  { id: 'E-cert-rotasyon', group: 'E', feature: 'Sunucu sertifikası yenilenince APK\'ya gömülü ilk pin\'ler (bootstrap) eskiyor: eski APK başlatılamıyor, yeni değerlerle derlenince bağlanıyor', scenarios: ['E03'] },
  { id: 'E-yedek-anahtar', group: 'E', feature: 'Sertifikanın saklı yedek anahtarına geçiş: config sunucusunda uygulama yeniden derlenmeden bağlanmaya devam ediyor; hedef host\'ta pin uyuşmazlığı olmadan, config yenilenmeden bağlanıyor', scenarios: ['E10'] },
  { id: 'E-bootstrap-yukleme', group: 'E', feature: 'Bootstrap sekmesinden JKS yükleme (server-tls-pins/upload): pin dosyası da, yeniden başlatmadan sonra sunucunun sunduğu sertifika da yüklenen anahtar çiftine geçiyor', scenarios: ['E03'] },
  { id: 'E-cert-sure', group: 'E', feature: 'Sertifika süresi izleme: cert-expiry ucunda expired/warning, dashboard kartı, açılışta CRITICAL/WARNING logu', scenarios: ['E04'] },
  { id: 'E-config-api-yonetim', group: 'E', feature: 'Config API oluştur/durdur/başlat/sil (silinince host\'ları da gidiyor); aynı porta ikincisi açılınca önceki duruyor', scenarios: ['E05'] },
  { id: 'E-host-dogrulama', group: 'E', feature: 'ping-remote (canlı pin\'ler kayıtlı pin\'lerle eşleşiyor, komut enjeksiyonu reddediliyor) ve test-connection', scenarios: ['E05'] },
  { id: 'E-fetch-cert-url', group: 'E', feature: 'fetch-cert-url: var olan host\'un pin\'leri, host\'un şu an sunduğu sertifika zincirinden yenileniyor (sürüm +1, geçmişte cert_fetched); bu ucun arayüzde düğmesi yok', scenarios: ['E05'] },
  { id: 'E-pin-gecmisi', group: 'E', feature: 'Pin değişiklik geçmişi; host silinip geri eklenince sürüm kaldığı yerden devam ediyor (watermark: en yüksek sürüm hatırlanıyor)', scenarios: ['E06'] },
  { id: 'E-telemetri', group: 'E', feature: 'Bağlantı Geçmişi / Bağlı Cihazlar, sayfalama; bozuk cihaz raporu (client-report) 400; client-devices ucu anahtar istiyor', scenarios: ['E07'] },
  { id: 'E-docker', group: 'E', feature: 'docker compose down/up: pin, vault, sertifika ve anahtarlar kalıyor; Config API\'ler ve mock host\'lar kendiliğinden başlıyor', scenarios: ['E08'] },
  { id: 'E-keystore-parolasi', group: 'E', feature: 'KEYSTORE_PASSWORD: sunucunun keystore dosyaları (JKS) bu parolayla yazılıyor, varsayılan "changeit" parolasıyla açılmıyor (keytool çıktısı)', scenarios: ['E08'] },
  { id: 'E-pin-kapsami', group: 'E', feature: 'wantPinsFor + cihaz bazlı host izin listesi: liste boşken hiç pin gelmiyor (şüphede bağlantıya izin vermez), izin verilince yalnızca o host\'un pin\'leri', scenarios: ['E09'] },
  // ── A (pin yönetimi ve imzalı config) ─────────────────────────────────
  { id: 'A-telemetri', group: 'A', feature: 'Bağlantı olayları ve sunucuya giden cihaz raporları (telemetri): Bağlı Cihazlar, Bağlantı Geçmişi', scenarios: ['01'] },
  { id: 'A-rotasyon', group: 'A', feature: 'Uzaktan pin config: yedek pin ekleme/çıkarma, host başına sürüm, applyTo istemcisi yeniden kurulmadan yeni pin\'leri kullanıyor, updateNow', scenarios: ['02'] },
  { id: 'A-kurtarma', group: 'A', feature: 'Pin uyuşmazlığında config kendiliğinden yenileniyor ve istek tekrar deneniyor (PinRecoveryInterceptor)', scenarios: ['03'] },
  { id: 'A-force', group: 'A', feature: 'forceUpdate: aynı sürümdeki config yeniden uygulanıyor, kapatılınca normale dönülüyor', scenarios: ['04'] },
  { id: 'A-prodstyle', group: 'A', feature: 'PinVault\'u import etmeyen istemci pinsForHost/currentPins ile pinleniyor ve uyuşmazlıktan kendisi toparlanıyor', scenarios: ['05'] },
  { id: 'A-host-sil', group: 'A', feature: 'Bilinmeyen host\'a istek reddediliyor; host silinip geri eklenince sürüm kaldığı yerden devam ediyor (watermark)', scenarios: ['08'] },
  { id: 'A-bos-config', group: 'A', feature: 'Boş config reddediliyor (en az 1 host kuralı), eski config\'le devam ediliyor', scenarios: ['09'] },
  { id: 'A-pin-bicim', group: 'A', feature: 'Hatalı biçimli pin reddediliyor (44 karakter / 32 bayt olmalı); dashboard da doğruluyor', scenarios: ['10'] },
  { id: 'A-workmanager', group: 'A', feature: 'WorkManager ile periyodik güncelleme: yeni config düğmeye basmadan geliyor', scenarios: ['11'] },
  { id: 'A-workmanager-yonetim', group: 'A', feature: 'WorkManager işi: getScheduledWorkInfo listeliyor, cancelPeriodicUpdates işi JobScheduler\'dan (Android\'in iş planlayıcısı) kaldırıyor, schedulePeriodicUpdates geri getiriyor (dumpsys jobscheduler)', scenarios: ['A27'] },
  { id: 'A-sertifika-gecerlilik', group: 'A', feature: 'Sunucu sertifikasının geçerlilik tarihi: süresi dolmuş sertifikalı host "expired or not yet valid" ile reddediliyor, kurtarma (config yenileme) tetiklenmiyor; sertifika yenilenince bağlantı dönüyor', scenarios: ['E04'] },
  { id: 'A-tek-pin', group: 'A', feature: 'Host başına en az 2 farklı pin kuralı: tek pin de aynı pinin iki kopyası da reddediliyor (dashboard formu ve sunucu 400), telefon etkilenmiyor', scenarios: ['A16'] },
  { id: 'A-wildcard', group: 'A', feature: 'Joker alan adıyla pin eşleşmesi: *.example.com tek alt alan adını eşliyor, *.com gibi aşırı geniş joker güvenlik için yok sayılıyor', scenarios: ['A17'] },
  { id: 'A-tazelik', group: 'A', feature: 'İmzalı config\'in geçerlilik süresi (issuedAt/expiresAt, CONFIG_TTL_SECONDS): süresi geçmiş config reddediliyor, telefon eski config\'le çalışıyor', scenarios: ['A18'] },
  { id: 'A-imza-dogrulama', group: 'A', feature: 'Config imzası (ECDSA) doğrulanıyor; imzalama anahtarı değişince (rotasyon) eski public key\'li APK config\'i reddediyor ve sıfırdan açılamıyor, yeni anahtarla derlenince kabul ediyor', scenarios: ['A19'] },
  { id: 'A-sertifika-rotasyon', group: 'A', feature: 'Mock host\'un sertifikası gerçekten yenileniyor: pin\'ler değişiyor, sürüm artıyor; eski pin\'lerle bağlantı reddediliyor, config yenilenince bağlantı dönüyor', scenarios: ['A20'] },
  { id: 'A-ara-sertifika-pini', group: 'A', feature: 'CA (ara sertifika) pini: telefon, pinlenen CA\'nın imzaladığı sertifikayı sitenin kendi pini listede olmadan kabul ediyor; gerçek CA sertifikasını sahte sertifikanın arkasına ekleyen saldırganı reddediyor (saldırgana istek ulaşmıyor)', scenarios: ['A21'] },
  { id: 'A-ozel-istemci', group: 'A', feature: 'getClient(HttpConnectionSettings): pinliyor ama otomatik kurtarma yok, uyuşmazlık kendiliğinden düzelmiyor', scenarios: ['A25'] },
  { id: 'A-reset', group: 'A', feature: 'reset(): config silinince pinli istemci kurulamıyor, TLS hiç denenmiyor (şüphede bağlantıya izin vermez); "Sıfırla ve başlat" ile geri geliyor', scenarios: ['A26'] },
  { id: 'A-cift-init', group: 'A', feature: 'init ikinci kez çağrılınca ağa çıkmadan "Ready" dönüyor (yeni TLS bağlantısı açılmıyor)', scenarios: ['A26'] },
  { id: 'A-telemetri-secenek', group: 'A', feature: 'Cihaz raporu (telemetri) seçenekleri: başarılı bağlantıları raporlamamak, aynı kaydı bir süre tekrar göndermemek; hatalar bu süzgece takılmıyor; config_updated / config_update_failed kayıtları', scenarios: ['A31'] },
  // ── B (mTLS) ──────────────────────────────────────────────────────────
  { id: 'B-kayit', group: 'B', feature: 'Token ile kayıt, X-P12-SHA256 ile dosya doğrulaması, mTLS bağlantısı, iptal edilince red, kayıt silme', scenarios: ['12'] },
  { id: 'B-mtls-config', group: 'B', feature: 'Config mTLS Config API\'den: ana config bloğu istemci sertifikası sunuyor, sertifikasız bağlantı el sıkışmada reddediliyor; API\'de host yokken pin uygulanmıyor (şüphede bağlantıya izin vermez)', scenarios: ['B01'] },
  { id: 'B-host-sertifikasi', group: 'B', feature: 'Host\'a özel istemci sertifikası (HostPin.mtls + clientCertVersion): dashboard\'dan yükleme, sürüm artışı; TLS Config API 403 veriyor, mTLS Config API\'den iniyor', scenarios: ['B02'] },
  { id: 'B-composite-keymanager', group: 'B', feature: 'Composite KeyManager sertifikayı host\'a göre seçiyor: Config API\'ye kayıt sertifikası, mock mTLS host\'a ona özel sertifika (kayıt sertifikası iptal edilince yalnızca Config API reddediyor)', scenarios: ['B03'] },
  { id: 'B-otomatik-kayit', group: 'B', feature: 'Otomatik kayıt (autoEnroll): ENROLLMENT_MODE=open iken cihaz ANDROID_ID ile sertifika alıyor, token modunda reddediliyor', scenarios: ['B04'] },
  { id: 'B-elle-p12', group: 'B', feature: 'Elle verilen P12 (ConfigApiBlock.clientKeystore): kayıt olmadan mTLS Config API\'ye ve mock mTLS host\'a bağlanılıyor, sonra P12 bırakılıyor', scenarios: ['B05'] },
  { id: 'B-token-yasam', group: 'B', feature: 'Kayıt token\'ı tek kullanımlık ve süreli (ENROLLMENT_TOKEN_TTL_SECONDS); listede yalnızca token\'ın maskeli başı ve "Kullanıldı" durumu görünüyor', scenarios: ['B06'] },
  { id: 'B-unenroll', group: 'B', feature: 'Kaydı silme (unenroll): uygulama kapanmadan bellekteki istemci anahtarı boşalıyor, cihazda kayıt kalmıyor, yeniden açılışta da reddediliyor (sunucudaki sertifika hâlâ geçerliyken)', scenarios: ['B07'] },
  { id: 'B-truststore', group: 'B', feature: 'Truststore (sunucunun güvendiği istemci sertifikaları): dışarıda üretilmiş PEM yükleme, o anahtar çiftiyle mTLS bağlantısı, iptal edilince red', scenarios: ['B08'] },
  { id: 'B-api-durdur', group: 'B', feature: 'mTLS Config API durdurulup başlatılıyor: TLS modundaki cihaz "Hazır" kalıyor, mTLS config modundaki cihaz saklı config\'le devam ediyor ama config\'i yenileyemiyor', scenarios: ['B09'] },
  // ── C (vault) ─────────────────────────────────────────────────────────
  { id: 'C-public', group: 'C', feature: 'Vault: public dosya indirme, içerik imzası, değişmemişse 304/AlreadyCurrent, yeni sürüm, dağıtım geçmişi', scenarios: ['13'] },
  { id: 'C-token', group: 'C', feature: 'Vault token politikası: token yoksa 401, cihazın token\'ıyla iniyor, iptal edilince 401', scenarios: ['14'] },
  { id: 'C-e2e', group: 'C', feature: 'Vault cihaza özel şifreleme (end_to_end; AES-GCM, dosya anahtarı cihazın RSA anahtarıyla şifreli, RSA-OAEP): ağ trafiğinde şifreli, cihazda çözülüyor; şifrelemeyi sunucu yapar, içeriği sunucu görür ama diskinde şifreli saklar', scenarios: ['15'] },
  { id: 'C-at-rest', group: 'C', feature: 'Vault at_rest: SQLite\'taki kayıt AES-256-GCM ile şifreli ("VLT-ENC1" + salt + IV), düz metin DB dosyasında hiç yok; ağ trafiğinde gövde şifresiz + X-Vault-Encryption: at_rest', scenarios: ['C01'] },
  { id: 'C-api-key', group: 'C', feature: 'Vault api_key: kütüphane yönetim anahtarını göndermediği için telefon 401 alıyor, X-API-Key ile istek 200 alıyor; dağıtım geçmişinde failed kaydı, nedeni ve authMethod', scenarios: ['C02'] },
  { id: 'C-token-mtls', group: 'C', feature: 'Vault token_mtls: token ve istemci sertifikası birlikte gerekiyor; sertifikadaki kimlik (CN) X-Device-Id\'ye ya da device_uid\'ye uymalı; sertifikasız bağlantı el sıkışmada düşüyor, TLS portunda geçerli token bile 401 alıyor, başka cihazın sertifikasıyla "Device identity mismatch"', scenarios: ['C03'] },
  { id: 'C-depolama', group: 'C', feature: 'Vault dosyasının telefonda saklanma biçimleri: ENCRYPTED_FILE (files/vault_files/<key>.enc, [iv_len][iv] + AES-256-GCM, anahtar Keystore\'da) ve ENCRYPTED_PREFS (pinvault_vault_files.xml, kayıt adı ve değeri şifreli)', scenarios: ['C04'] },
  { id: 'C-esitleme', group: 'C', feature: 'syncAllFiles ve WorkManager eşitlemesi: yalnızca updateWithPins dosyaları, değişmemişse 304 → AlreadyCurrent, yeni sürüm düğmeye basmadan arka planda iniyor', scenarios: ['C05'] },
  { id: 'C-cevrimdisi', group: 'C', feature: 'Host kapalıyken loadFile/hasFile/fileVersion saklı dosyayı okuyor, aynı anda indirme (fetch) düşüyor; clearFile .enc dosyasını, sürüm kaydını, şifreli tercih kaydını ve Keystore anahtarını siliyor', scenarios: ['C06'] },
  { id: 'C-politika-degisimi', group: 'C', feature: 'Erişim politikası dashboard\'dan değiştiriliyor (PUT …/vault/{key}/policy): public → token → public; içerik ve sürüm değişmiyor, telefon her adımda yeni politikaya uyuyor', scenarios: ['C07'] },
  { id: 'C-dagitim', group: 'C', feature: 'Dağıtım geçmişi ve istatistikler: downloaded / cached / failed, hata nedeni ve authMethod; stats ucu, durum süzgeci, cihaz detayı, dosya detayı (sürüm zaman çizgisi)', scenarios: ['C08'] },
  { id: 'C-vault-enabled', group: 'C', feature: 'Vault\'u kapatma ayarı (vault_enabled): her Config API için ayrı kaydediliyor (varsayılan dahil) ve indirmeyi gerçekten durduruyor; kapalıyken her dosya adı 403 alıyor (var olan da olmayan da), yönetim uçları çalışıyor', scenarios: ['C09'] },
  { id: 'C-e2e-anahtar-yok', group: 'C', feature: 'end_to_end: anahtarı kayıtlı olmayan cihaz 412 + "public key" mesajı, kimliksiz istek 401; kayıtlı cihaza giden pakette dosya anahtarı onun RSA anahtarıyla şifreli (256 bayt)', scenarios: ['C10'] },
  { id: 'C-sifreleme-basligi', group: 'C', feature: 'Sunucunun X-Vault-Encryption başlığı uygulamadaki VaultFileEncryption ayarının önüne geçiyor: plain tanımlı dosya end_to_end gelince yine çözülüyor, imza şifresiz içerik üzerinden doğrulanıyor', scenarios: ['C11'] },
  // ── D (telefonda şifreli saklama) ─────────────────────────────────────
  { id: 'D-config-deposu', group: 'D', feature: 'Telefonda saklanan pin config\'i şifreli: ssl_cert_config_<id>.xml içinde host adı, IP ve pin\'ler açık metin geçmiyor, kayıt adları da şifreli; Tink anahtarları Android Keystore\'daki ana anahtarla şifreli', scenarios: ['D01'] },
  { id: 'D-istemci-sertifikasi', group: 'D', feature: 'İstemci sertifikası (P12) şifreli: pinvault_client_cert.xml\'deki ham kayıt PKCS12 olarak açılmıyor ve CN açık metinde yok; kütüphane ise kaydı çözüp CN\'i okuyor ve mTLS bağlantısında kullanıyor', scenarios: ['D02'] },
  { id: 'D-cihaz-anahtari', group: 'D', feature: 'Cihazın RSA anahtarı Keystore\'da: adı pinvault_vault_e2e_rsa, 2048 bit, donanım desteği bilgisi; public key hash\'i (SPKI SHA-256) sunucudaki kayıtlı PEM ile birebir aynı, private key uygulama dosyalarında yok', scenarios: ['D03'] },
  { id: 'D-force-kalicilik', group: 'D', feature: 'forceUpdate bayrağı saklı config\'te kalıcı (açılışta ağdan önce depodan okunuyor); kapatılınca sürüm değişmese de saklı kopyadan siliniyor (sonuç "Config güncel" kalıyor, yalnızca bayrak diske yazılıyor)', scenarios: ['D04'] },
  { id: 'D-yedekleme', group: 'D', feature: 'Uygulama verisi cihaz yedeğine girmiyor: yerel yedeklemede bmgr backupnow "Backup is not allowed" diyor; birleştirilmiş manifest\'te allowBackup=false, kütüphanenin yedekleme kuralları APK\'da; kuralların Config API kimliklerini tek tek elle sayması bulgu olarak belgelendi', scenarios: ['D05'] },
  // ── F (sunucuya ulaşılamadığında) ─────────────────────────────────────
  { id: 'F-ilk-acilis', group: 'F', feature: 'Host kapalıyken ilk açılış: şüphede bağlantıya izin vermiyor, sistem sertifikalarına güvenmeye dönmüyor; host dönünce toparlanıyor', scenarios: ['06'] },
  { id: 'F-init-retry', group: 'F', feature: 'Başlatma (init) 3 kez deneniyor, bekleme her denemede 2 sn × deneme sayısı (logcat: "Update attempt n/3", "retrying in 2000/4000ms"); üçü de düşünce init başarısız', scenarios: ['06'] },
  { id: 'F-onbellek', group: 'F', feature: 'Host kapalıyken sonraki açılış: saklı (şifreli) config\'le çalışıyor', scenarios: ['07'] },
  { id: 'F-force-offline', group: 'F', feature: 'forceUpdate açıkken sunucuya ulaşılamazsa init başarısız (ForceUpdateFailedException); host dönünce "Tekrar dene" toparlıyor. Dashboard\'da tek host için açılan force bayrağı da aynı kontrolü çalıştırıyor (sunucu gönderdiği config\'i hasAnyForceUpdate ile işaretlediği için)', scenarios: ['F01'] },
  { id: 'F-devre-kesici', group: 'F', feature: 'Otomatik kurtarmanın yeniden deneme freni: 5 dk içinde 3 başarısız kurtarmadan sonra 10 dk denenmiyor; dördüncü istekte config yenileme isteği yapılmıyor, elle yenileme çalışmaya devam ediyor', scenarios: ['F02'] },
  { id: 'F-telemetri-kesik', group: 'F', feature: 'Cihaz raporu (telemetri) ucu erişilemezken uygulama akıcı: raporlar ayrı thread\'de, sınırlı kuyrukta; pinli istekler ve config yenileme gecikmiyor', scenarios: ['F03'] },
  // ── G (araya girme saldırıları; emülatörde iptables DNAT + saldırgan proxy) ─
  { id: 'G-araya-girme', group: 'G', feature: 'Gerçek araya girme: sahte anahtarlı sunucuya tek HTTP isteği bile gitmiyor (bağlantı fatal TLS alert ile kesiliyor), saklı config\'li uygulama yenileyemiyor ama çalışıyor, boş kurulum hiç açılmıyor (şüphede bağlantıya izin vermez); saldırgan sertifikasının pin\'i dashboard\'a pin_mismatch olarak düşüyor', scenarios: ['G01'] },
  { id: 'G-config-imza', group: 'G', feature: 'Config imzası (ECDSA) doğrulanıyor, signaturePublicKey zorunlu: saldırgan imzanın tek baytını değiştirince config uygulanmıyor, saklı config ve pinli bağlantı etkilenmiyor; saldırgan değiştirmeyi bırakınca bekleyen sürüm iniyor', scenarios: ['G02'] },
  { id: 'G-replay', group: 'G', feature: 'Eski yanıtı tekrar gönderme reddediliyor: imzası geçerli ama daha eski tarihli (issuedAt) bir yanıt tekrar gönderilince telefon kabul etmiyor; saklı config korunuyor', scenarios: ['G03'] },
  { id: 'G-ayni-zarf', group: 'G', feature: 'Birebir aynı imzalı yanıtın tekrar gelmesi saldırı sayılmıyor: telefon "Config güncel" diyor, hiçbir şey yazılmıyor (imzayı değişiklik kaydedilir kaydedilmez bir kez atan HSM/KMS/önbellek/CDN kurulumları için)', scenarios: ['G03'] },
  { id: 'G-sahte-anahtar-seti', group: 'G', feature: 'Sahte anahtar seti (telefonun güvendiği imza anahtarlarının listesi): saldırgan yanıta kurtarma anahtarıyla değil imzalama anahtarıyla imzalanmış bir set ekleyince bütün yanıt reddediliyor ("Signing-key set rejected — 0 of 1 required recovery signature(s) valid"); güvenilen anahtarlar ve saklı config değişmiyor, pinli istek sürüyor; kurtarma anahtarıyla imzalı set ise uygulanıyor ve kalıcı', scenarios: ['G09'] },
  { id: 'G-surum-dusurme', group: 'G', feature: 'Host\'un pin config\'ini eski sürüme geri döndürme reddediliyor: sürümü düşürülüp yeniden imzalanmış config (imzası geçerli, issuedAt yeni) kabul edilmiyor', scenarios: ['G04'] },
  { id: 'G-p12-butunluk', group: 'G', feature: 'Saldırgan kayıt yanıtından X-P12-SHA256 başlığını silince kayıt reddediliyor: P12 diske yazılmadan önce doğrulanıyor, cihazda sertifika kalmıyor; sunucuda sertifikanın yine de üretilip token\'ın harcandığı işletim notu olarak belgelendi', scenarios: ['G05'] },
  { id: 'G-vault-imza', group: 'G', feature: 'Vault içerik imzası: saldırgan imzayı bozunca "signature verification FAILED", imza başlığını silince "no X-Vault-Signature … fail-closed"; iki durumda da saklı sürüm ve içerik korunuyor', scenarios: ['G06'] },
  { id: 'G-vault-surum', group: 'G', feature: 'Vault dosyasını eski sürüme geri döndürme reddediliyor: sürüm imzalanan standart metnin içinde olduğu için yalnızca başlığı değiştirmek imzayı bozuyor; yeniden imzalansa bile ayrı bir sürüm kontrolü ("downgrade rejected") devrede', scenarios: ['G07'] },
  { id: 'G-guncelleme-sagligi', group: 'G', feature: 'Güncellemeden sonra sağlık kontrolü ve geri alma: /health 500 dönünce uygulama "başlatılamadı" diyor ve uygulanan config geri alınıyor (önceki kopya geri yazılıyor, yoksa depo temizleniyor); sağlık bozukken ikinci açılış da başlatılamıyor', scenarios: ['G08'] },
  // ── H (kendi sunucusuyla ya da sunucusuz kullanım) ────────────────────
  { id: 'H-ozel-uclar', group: 'H', feature: 'Özel API yolları (configEndpoint=ssl/pins, healthEndpoint=ping, vaultFile endpoint=files/<key>, vaultReportEndpoint=analytics/vault): uygulama config\'i ve vault dosyasını testin kendi açtığı, kendi imzalayan backend\'den alıyor; ana host bu sürede tek config/vault isteği almıyor', scenarios: ['H01'] },
  { id: 'H-ozel-api', group: 'H', feature: 'Özel CertificateConfigApi ("Gömülü API" modu, uygulama içi): Config API portu iptables ile kesikken TLS modu açılamıyor, bu mod sıfırdan Hazır oluyor; kütüphaneden hiç HTTP çıkmıyor', scenarios: ['H02'] },
  { id: 'H-statik', group: 'H', feature: 'Statik (sunucusuz) mod: pin\'ler APK\'nın içinde; host container\'ı kapalıyken bile pinli bağlantı kuruluyor; vault dosyası ve kayıt bu modda kullanılamıyor', scenarios: ['H03'] },
  // ── S (imza anahtarlarının korunması; isteğe bağlı) ───────────────────
  { id: 'S-yedek-anahtar', group: 'S', feature: 'Çevrimdışı saklanan yedek imza anahtarı (public yarısı APK\'da, signaturePublicKeys): birincil anahtar kaybolunca operatör yedeği signing-keys.sh install ile sunucuya kuruyor; telefon aynı APK\'yla (base.apk sha256 değişmedi) config almaya devam ediyor, verisi silinmiş kurulum da açılıyor, imzalayan olarak yedek anahtarı gösteriyor', scenarios: ['S01'] },
  { id: 'S-anahtar-seti-dondurme', group: 'S', feature: 'Anahtar seti ile anahtar değiştirme (rotasyon): APK\'da olmayan yeni anahtar (lab-next) ikinci imzalayıcı olarak ekleniyor; kurtarma anahtarıyla imzalı anahtar seti (telefonun güvendiği imza anahtarlarının listesi) signing-keys.sh keyset/upload ile yüklenince telefon seti uyguluyor (Depolama: set sürümü, güvenilen anahtar kimlikleri, kurtarma anahtarı)', scenarios: ['S02'] },
  { id: 'S-anahtar-seti-iptal', group: 'S', feature: 'Anahtar iptali: eski birincil anahtarı listelemeyen set (yükleme yanıtı uyarı veriyor) uygulanınca o anahtara artık güvenilmiyor; onunla imzalı config "Signed by a key revoked by signing-key set vN" ile reddediliyor, saklı config\'le pinli bağlantı sürüyor; set uygulama yeniden açılınca da geçerli (pinvault_signing_keys.xml)', scenarios: ['S02'] },
  { id: 'S-anahtar-seti-sunucu-kapisi', group: 'S', feature: 'Sunucu yüklenen seti telefonla aynı kurallarla doğruluyor: kurtarma anahtarıyla imzalanmamış set 422 (dashboard\'da "Set reddedildi"), sunucunun imzalamada kullandığı anahtarlardan hiçbirini içermeyen set 409; anahtar seti etkinken "Anahtarı Yenile" düğmesi kapalı, API 409', scenarios: ['S02'] },
  { id: 'S-m-of-n', group: 'S', feature: 'Çoklu imza (Ayarlar\'dan en az 2 imza şartı, requiredSignatures=2): tek imzalı config "1 of 2 required signatures valid" ile reddediliyor (uygulama başlatılamıyor); iki imzalayıcıyla (CONFIG_SIGNERS=local,local:second) imzalı yanıtta iki imza var, "Tekrar dene" ile Hazır, telefon iki anahtar kimliğini gösteriyor', scenarios: ['S03'] },
  { id: 'S-m-of-n-vault', group: 'S', feature: 'Vault dosyası da iki imzalı (X-Vault-Signature + X-Vault-Signatures; iki imza da imzalanan standart metin üzerinde geçerli): en az 2 imza isteyen telefon dosyayı indirip doğruluyor', scenarios: ['S03'] },
  { id: 'S-hsm', group: 'S', feature: 'HSM ile imzalama (SoftHSM, PKCS#11): anahtar HSM\'in içinde üretiliyor, dışarı çıkarılamıyor ("sensitive, always sensitive, never extractable") ve yalnızca imza atabiliyor (Usage: sign; pkcs11-tool), data/ altında dosyası yok; dashboard pkcs11 imzalayıcısını gösteriyor; anahtar setiyle telefonlara bildirilip yerel anahtar devreden çıkarılınca telefon HSM\'in imzaladığı config\'i kabul ediyor', scenarios: ['S04'] },
  { id: 'S-komut-imzalayici', group: 'S', feature: 'Harici komutla imzalama (KMS benzeri, SIGNER_INPUT=digest): imzayı harici bir komut atıyor (komuta 32 baytlık özet gidiyor), komutun çağrı günlüğü her imzayı gösteriyor; anahtar setiyle telefonlara bildirilip yalnızca komut imzalarken telefon kabul ediyor; komut yanlış anahtarla imzalayınca sunucu imzayı doğrulayıp yanıtı vermiyor (503; nedeni yalnızca sunucu günlüğünde)', scenarios: ['S05'] },
  { id: 'S-imza-onbellegi', group: 'S', feature: 'İmza önbelleği (CONFIG_SIGNATURE_CACHE): aynı yanıtı tekrar kabul edebildiğini bildiren (yeni sürüm) uygulamaya bayt bayt aynı imzalı yanıt, bildirmeyene yeni imza; telefonun sorguları önbellekten (imza sayacı artmıyor), aynı yanıt "Config güncel"; pin değişikliği kaydedilir kaydedilmez imzalanıyor (sayaç cihaz sorgusundan önce artıyor), cihaz o imzayı alıyor', scenarios: ['S06'] },
  // ── Y (değişiklik denetimi ve onay; isteğe bağlı) ─────────────────────
  { id: 'Y-kisisel-anahtar', group: 'Y', feature: 'Kişiye özel yönetici anahtarları (ADMIN_KEYS; sunucuda yalnızca SHA-256 hash\'leri): dashboard anahtarın sahibini gösteriyor (kimlik rozeti "alice"), paylaşılan API_KEY "admin" olarak kalıyor; pin değişikliği kişinin adıyla kaydediliyor; yanlış anahtar 403 ve auth_failed kaydı (kim: unknown, kaynak IP; dakikanın ilk denemesi hemen, aynı dakikadakiler dakika sonunda tek özet satırında)', scenarios: ['Y01'] },
  { id: 'Y-denetim-kaydi', group: 'Y', feature: 'Denetim kaydı: alice\'in pin değişikliği (telefon yeni sürümü alıyor) pins_changed olarak host bazlı farkla (önceki/sonraki sürüm ve pin\'ler, kaynak IP, kayıtları birbirine bağlayan zincir hash\'i) listeleniyor, işlem türüne göre süzülebiliyor; "Zinciri Doğrula" sağlam, kayıt sayısıyla', scenarios: ['Y01'] },
  { id: 'Y-webhook', group: 'Y', feature: 'Anında bildirim (NOTIFY_WEBHOOK_URL/SECRET): pins_changed ve auth_failed webhook\'a gidiyor; X-PinVault-Signature (paylaşılan gizli anahtarla imza, HMAC) doğru; gövdedeki auditId/auditHash denetim kaydıyla aynı; dashboard\'un bildirim kartı teslimatı (HTTP 204) gösteriyor', scenarios: ['Y01'] },
  { id: 'Y-zincir-kurcalama', group: 'Y', feature: 'Denetim kaydı sonradan değiştirilirse fark ediliyor (geçici test sunucusunda): sqlite3 ile doğrudan UPDATE ve DELETE veritabanı kuralıyla (trigger) reddediliyor ("audit_log is append-only"); kural silinip bir satırın özeti yeniden yazılınca saklı hash tutmuyor ve "Zinciri Doğrula" tam o satırı bozuk gösteriyor', scenarios: ['Y02'] },
  { id: 'Y-iki-kisi-onayi', group: 'Y', feature: 'İki kişi onayı (PIN_CHANGE_APPROVALS=2): alice\'in pin değişikliği 202 ile beklemeye alınıyor ("Onaylar" rozeti, telefon eski sürümde); alice kendi isteğini onaylayamıyor (düğme kapalı, 409), paylaşılan API_KEY ne onaylayabiliyor ne de değişiklik isteyebiliyor (409); bob onaylayınca uygulanıyor, telefon yeni sürümü alıyor; denetim kaydında pins_changed "alice (approved by bob)", change_applied ve reddedilen onay denemeleri (isteğin Config API\'si ve hedefiyle); Config API portu (6651) pin yazımını 409 ile reddediyor', scenarios: ['Y03'] },
  { id: 'Y-onay-reddi', group: 'Y', feature: 'Ret, Config API durdurmanın da onaya bağlı olması ve eskimiş istek: bob\'un gerekçeyle reddettiği istek uygulanmıyor; varsayılan Config API\'yi durdurmak da onay istiyor (202, onay kartında "Config API başlat/durdur"), bob reddedince Config API çalışmaya, telefon config almaya devam ediyor; karara bağlanan isteklerin saklanan içeriği siliniyor; aynı pin\'ler için açılan iki istekten biri onaylanınca diğeri 409 "changed after … was requested" alıyor (eskimiş istek: pin\'ler bu arada değişti)', scenarios: ['Y03'] },
  { id: 'Y-canli-kapi-enforce', group: 'Y', feature: 'Canlı sertifika kontrolü, engelleme modu (PIN_LIVE_CHECK=enforce, LIVE_CHECK_HOST_MAP): host\'un şu an sunduğu sertifikanın pin\'ini içermeyen pin listesi 422 ile reddediliyor, dashboard o sertifikayı gösterip gerekçe istiyor; gerekçe boşsa kaydedilmiyor ve telefon mock host\'a bağlanmaya devam ediyor; "Canlı Kontrol" düğmesi kaydetmeden aynı sonucu veriyor (✗ / ✓); o sertifikayı içeren liste kontrolden geçiyor', scenarios: ['Y04'] },
  { id: 'Y-canli-kapi-override', group: 'Y', feature: 'Gerekçe yazıp yine de kaydetme: gerekçe sorusu yanıtlanınca liste ?liveCheckOverride ile kaydediliyor, live_check_overridden gerekçesiyle denetim kaydına ve webhook\'a (HMAC imzası doğru) düşüyor; bu yanlış listeyi alan telefon mock host\'a pin uyuşmazlığı yüzünden bağlanamıyor (kontrolün önlediği tam da bu); uyarı modunda (warn) liste kaydediliyor ama uyarı veriliyor (X-PinVault-Live-Check: warn, live_check_warning)', scenarios: ['Y04'] },
];

module.exports = { GROUPS, FEATURES };
