package com.example.pinvault.server.store

import kotlinx.serialization.Serializable
import java.security.MessageDigest

/**
 * Per-device, per-file access tokens for vault_files entries with
 * access_policy = "token" or "token_mtls".
 *
 * Design:
 *   - Tokens are stored as SHA-256 hashes only. The plaintext is generated by
 *     VaultAccessTokenService and shown to the admin ONCE; it is never logged
 *     or returned again.
 *   - UNIQUE(config_api_id, vault_key, device_id) enforces "one active token
 *     per device+file". Issuing a new token replaces the existing row — the
 *     previous token becomes invalid automatically.
 *   - Revocation is soft (revoked=1). The row is retained so audit logs remain
 *     joinable; validate() returns false for revoked rows.
 *   - validate() uses constant-time equality on the hash to resist timing
 *     oracles, even though an attacker would need to brute-force SHA-256.
 */
class VaultFileTokenStore(private val db: DatabaseManager) {

    /**
     * Persist a new token hash. If a prior row exists for the same
     * (configApiId, vaultKey, deviceId) triple it is overwritten (the old
     * token becomes invalid as its hash is no longer stored).
     */
    fun put(
        configApiId: String,
        vaultKey: String,
        deviceId: String,
        tokenPlaintext: String,
        timestamp: String
    ): Long {
        val hash = sha256Hex(tokenPlaintext)
        db.connection().use { conn ->
            // INSERT OR REPLACE on UNIQUE triple → old token hash is discarded.
            conn.prepareStatement("""
                INSERT OR REPLACE INTO vault_file_tokens
                    (config_api_id, vault_key, device_id, token_hash, created_at, revoked)
                VALUES (?, ?, ?, ?, ?, 0)
            """, java.sql.Statement.RETURN_GENERATED_KEYS).use { stmt ->
                stmt.setString(1, configApiId)
                stmt.setString(2, vaultKey)
                stmt.setString(3, deviceId)
                stmt.setString(4, hash)
                stmt.setString(5, timestamp)
                stmt.executeUpdate()
                val keys = stmt.generatedKeys
                return if (keys.next()) keys.getLong(1) else -1L
            }
        }
    }

    /**
     * Returns true iff there is an unrevoked token row for the exact triple
     * (configApiId, vaultKey, deviceId) whose hash equals SHA-256(plaintext).
     *
     * All three identifiers are verified — a token issued for device A cannot
     * be used by device B, nor for a different file key.
     */
    fun validate(
        configApiId: String,
        vaultKey: String,
        deviceId: String,
        tokenPlaintext: String
    ): Boolean {
        val expectedHash = sha256Hex(tokenPlaintext)
        db.connection().use { conn ->
            conn.prepareStatement("""
                SELECT token_hash FROM vault_file_tokens
                WHERE config_api_id = ? AND vault_key = ? AND device_id = ? AND revoked = 0
            """).use { stmt ->
                stmt.setString(1, configApiId)
                stmt.setString(2, vaultKey)
                stmt.setString(3, deviceId)
                val rs = stmt.executeQuery()
                if (!rs.next()) return false
                val storedHash = rs.getString("token_hash")
                return constantTimeEquals(storedHash, expectedHash)
            }
        }
    }

    fun revoke(tokenId: Long): Boolean {
        db.connection().use { conn ->
            conn.prepareStatement(
                "UPDATE vault_file_tokens SET revoked = 1 WHERE id = ?"
            ).use { stmt ->
                stmt.setLong(1, tokenId)
                return stmt.executeUpdate() > 0
            }
        }
    }

    fun revokeByTriple(configApiId: String, vaultKey: String, deviceId: String): Boolean {
        db.connection().use { conn ->
            conn.prepareStatement("""
                UPDATE vault_file_tokens SET revoked = 1
                WHERE config_api_id = ? AND vault_key = ? AND device_id = ?
            """).use { stmt ->
                stmt.setString(1, configApiId)
                stmt.setString(2, vaultKey)
                stmt.setString(3, deviceId)
                return stmt.executeUpdate() > 0
            }
        }
    }

    /** List tokens for a file (admin Token Management UI). */
    fun listForFile(configApiId: String, vaultKey: String): List<VaultFileTokenInfo> {
        db.connection().use { conn ->
            conn.prepareStatement("""
                SELECT id, config_api_id, vault_key, device_id, created_at, revoked
                FROM vault_file_tokens
                WHERE config_api_id = ? AND vault_key = ?
                ORDER BY id DESC
            """).use { stmt ->
                stmt.setString(1, configApiId)
                stmt.setString(2, vaultKey)
                val rs = stmt.executeQuery()
                return buildList {
                    while (rs.next()) add(VaultFileTokenInfo(
                        id = rs.getLong("id"),
                        configApiId = rs.getString("config_api_id"),
                        vaultKey = rs.getString("vault_key"),
                        deviceId = rs.getString("device_id"),
                        createdAt = rs.getString("created_at"),
                        revoked = rs.getInt("revoked") == 1
                    ))
                }
            }
        }
    }

    companion object {
        fun sha256Hex(input: String): String {
            val md = MessageDigest.getInstance("SHA-256")
            val bytes = md.digest(input.toByteArray(Charsets.UTF_8))
            return bytes.joinToString("") { "%02x".format(it) }
        }

        fun constantTimeEquals(a: String, b: String): Boolean {
            val aBytes = a.toByteArray()
            val bBytes = b.toByteArray()
            return MessageDigest.isEqual(aBytes, bBytes)
        }
    }
}

@Serializable
data class VaultFileTokenInfo(
    val id: Long,
    val configApiId: String,
    val vaultKey: String,
    val deviceId: String,
    val createdAt: String,
    val revoked: Boolean
)
