// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

// Flutter's Swift Package Manager support expects the plugin's manifest at
// `ios/<plugin_name>/Package.swift`, with the product name hyphen-separated
// (`pinvault-flutter`) and the target name as the package name (`pinvault_flutter`).
// The `FlutterFramework` dependency is generated by the Flutter tool at
// `ios/FlutterFramework`; PinVault is the native library this plugin bridges.
let package = Package(
    name: "pinvault_flutter",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .library(name: "pinvault-flutter", targets: ["pinvault_flutter"])
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
        // The FIRST PinVault release that includes `PinnedSession.webSocketTask(for:)`
        // (the API this plugin's pinned WebSocket calls). 2.4.2 does not have it,
        // so pin 2.4.3 (or later) once it is tagged. For a local-checkout build
        // before that release, use:  .package(name: "PinVault", path: "<checkout>")
        .package(url: "https://github.com/umutcansu/PinVault.git", from: "2.4.3"),
    ],
    targets: [
        .target(
            name: "pinvault_flutter",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                .product(name: "PinVault", package: "PinVault"),
            ]
        )
    ]
)
